language: rust

#before_script:
  #- (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  #- (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook)
  #- cargo install-update -a

script:
  #- mdbook build
  #- ./deploy -z
  - ./deploy --build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBTOKEN
  local-dir: book
  on:
    branch: master
    #branch: development

cache:
- cargo